name: Codesignex

on:
  push:
    branches:
      - main
  pull_request:
  merge_group: {}

concurrency:
  group: codesignex-${{ github.head_ref }}
  cancel-in-progress: true

env:
  MIX_ENV: test
  MISE_EXPERIMENTAL: 1

jobs:
  test:
    name: Test
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Restore Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('mix.lock') }}
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
  credo:
    name: Credo
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Restore Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('mix.lock') }}
      - name: Install dependencies
        run: mix deps.get
      - name: Run Credo
        run: mix credo
  format:
    name: Format
    runs-on: "ubuntu-latest"
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4 # v4
      - uses: jdx/mise-action@v2
      - name: Restore Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('mix.lock') }}
      - name: Install dependencies
        run: mix deps.get
      - name: Check format
        run: mix format --check-formatted